### ISSUE TITLE
Doesn't Include Lecture citation type. 

### ISSUE THREAD

**Issue by enzokarate** [wahspilihp/authoryear-unisa#2]
There is no way to cite a Lecture at the moment.

**Comment by wahspilihp** [comment]
I'd forgotten that because it wasn't in the HRG: I cited an online lecture recording an online source, as per p23.
 
    @Online{SEP1,
    	type = {lecture recording},
    	organization = {University of South Australia},
    	title = {Sustainable Engineering Practice},
    	urldate = {2018-03-29},
    	date = {2018-02-27},
    	author = {Smith, Elizabeth and Collett, Diana},
    	subtitle = {lecture recording 27 February 2018},
    	url = {https://lrsdownload.unisa.edu.au/echocontent/1809/1/9d6b9ad3-c57e-4e7b-9576-8d9ab3fd6de8/audio-vga.m4v},
    	note = {Course Outline and Work-Life balance},
    }

I suspect a lecture which isn't recorded would be counted as un-citeable as it doesn't exist in an accessible fixed medium, but I can ask the Learning Advisors.

**Comment by wahspilihp** [comment]
Fixed in commit 146ff4a
